drone_inventory/authentication/routes.py
from flask import Blueprint, render_template, redirect, request, url_for, flash
from drone_inventory.forms import UserLoginForm
from drone_inventory.models import User, db
from werkzeug.security import check_password_hash
from flask_login import login_user, logout_user, login_required

auth = Blueprint('auth', __name__, template_folder= 'auth_templates')


@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()
    try:
        if request.method == "POST" and form.validate_on_submit():
            email = form.email.data
            first_name = form.first_name.data
            last_name = form.first_name.data
            password = form.password.data

            user = User(email, password, first_name, last_name)

            db.session.add(user)
            db.session.commit()

            flash(f"You have succesfully created a user account {email}", "user-created")

            return redirect(url_for('auth.signin'))

    except:
        raise Exception('Invalid Form Data: Please Check Your Form')
        
    return render_template('signup.html', form = form)

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()
    try:
        if request.method == 'POST' and form.validate_on_submit:
            email = form.email.data
            password = form.password.data
            print(email, password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash("you were succesfully logged in via Email/Password","auth-success")
                return redirect(url_for('site.profile'))
    except:
        raise Exception('Invalid Form DATA: please check your form and try again')

    return render_template('signin.html', form = form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

drone_inventory/site/routes.py
from flask import Blueprint, render_template, request, redirect,url_for
from flask_login import login_required, current_user
from drone_inventory.forms import DroneForm
from drone_inventory.models import Drone, db
# from drone_inventory.helpers import random_joke_generator

site = Blueprint('site', __name__ , template_folder = 'site_templates')


"""
Note that in the above code, some arguemnts are apecified when creating the 
Blueprint object, The first argument, 'site', is the Blueprint's name, This is used
by Flask's routing mechanism. The second argumenet, __name__,  is the Blueprint's import name,
which Flask uses to locate the Blueprint's resources
"""

@site.route('/')
def home():
    return render_template('index.html')
@site.route('/profile', methods =['GET', 'POST'])
@login_required
def profile():
    my_drone = DroneForm()
    try:
        if request.method == 'POST' and my_drone.validate_on_submit():
            name = my_drone.name.data
            description = my_drone.description.data
            price = my_drone.price.data
            camera_quality = my_drone.camera_quality.data
            flight_time = my_drone.flight_time.data
            max_speed = my_drone.max_speed.data
            dimensions = my_drone.dimensions.data
            weight = my_drone.weight.data
            cost_of_production = my_drone.cost_of_production.data
            series = my_drone.series.data
            user_token = current_user.token

            drone = Drone(name, description, price, camera_quality, flight_time, max_speed, dimensions, weight, cost_of_production, series, user_token)

            db.session.add(drone)
            db.session.commit()

            return redirect(url_for('site.profile'))
    
    except:
        raise Exception('Drone not created, please check your form and try again!')
    user_token = current_user.token

    drones = Drone.query.filter_by(user_token = user_token)
    

    return render_template('profile.html', form = my_drone, drones = drones)

drone_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Drone Inventory API</title>
</head>
<body>
    <!-- NacBar Here -->
    <nav class="ct-nav">
        <div>
            <img src="../static/images/Coding Drones Logo.png">
        </div>
        <!--Nac Items -->
        <div>
            <ul id="horizontal-list">
                <a href="{{ url_for('site.home') }}">
                    <li>The Coding Drones Project</li>
                </a>
                <a href="{{ url_for('site.home') }}">
                    <li>Home</li>
                </a>

                <a href="{{ url_for('site.profile') }}">
                    <li>Profile</li>
                </a>
                {% if current_user.is_authenticated %}
                <a href="{{ url_for('auth.logout') }}">
                    <li>Logout</li>
                </a>
                {% else %}
                <a href="{{ url_for('auth.signup') }}">
                    <li>Sign Up</li>
                </a>
                <a href="{{ url_for('auth.signin') }}">
                    <li>Sign In</li>
                </a>
                {% endif %}
            </ul>
        </div>
    </nav>
    <!-- End of Navbar-->

    <!--Create space for content from other html pahes -->
    {% block content %}
    
    {% endblock content %}



<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

drone_inventory/templates/drone_form.html
<form method = "POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="name-field">
        {{ form.name.label }}
        {{ form.name(class = "form-control", placeholder = "Name!") }}
        </fieldset>
        <fieldset id="description-field">
        {{ form.description.label }}
        {{ form.description(class = "form-control", placeholder = "Description") }}
        </fieldset>
        <fieldset id="price-field">
        {{ form.price.label }}
        {{ form.price(class = "form-control", placeholder = "Price") }}
        </fieldset>
        <fieldset id="camera-field">
        {{ form.camera_quality.label }}
        {{ form.camera_quality(class = "form-control", placeholder = "Camera Quality") }}
        </fieldset>
        <fieldset id="flight-field">
        {{ form.flight_time.label }}
        {{ form.flight_time(class = "form-control", placeholder = "Flight Time") }}
        </fieldset>
        <fieldset id="max_speed-field">
        {{ form.max_speed.label }}
        {{ form.max_speed(class = "form-control", placeholder = "Max Speed") }}
        </fieldset>
        <fieldset id="dimensions-field">
        {{ form.dimensions.label }}
        {{ form.dimensions(class = "form-control", placeholder = "Dimensions") }}
        </fieldset>
        <fieldset id="weight-field">
        {{ form.weight.label }}
        {{ form.weight(class = "form-control", placeholder = "Weight") }}
        </fieldset>
        <fieldset id="cop-field">
        {{ form.cost_of_production.label }}
        {{ form.cost_of_production(class = "form-control", placeholder = "Cost of Production") }}
        </fieldset>
        <fieldset id="series-field">
        {{ form.series.label }}
        {{ form.series(class = "form-control", placeholder = "Series") }}
        </fieldset>
       

        <!-- Submit Area Button -->
        {{ form.submit_button(class = "btn btn-primary btn-block") }}

    </div>
</form>

drone_inventory/templates/forms.html
<form method = "POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Place Email Here!") }}
        </fieldset>
        <fieldset id="first-field">
            {{ form.first_name.label }}
            {{ form.first_name(class = "form-control", placeholder = "First Name") }}
        </fieldset>
        <fieldset id="last-field">
            {{ form.last_name.label }}
            {{ form.last_name(class = "form-control", placeholder = "Last Name") }}
        </fieldset>
        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "password") }}
        </fieldset>

        {{ form.submit_button(class = "btn btn-primary btn-block") }}    </div>
</form>